// auth-client-vue/app/components/auth/MagicLinkForm.vue
<!-- components/auth/MagicLinkForm.vue -->
<template>
  <div class="space-y-4">
    <h2 class="text-lg font-semibold">Login with magic link</h2>

    <form v-if="!success" @submit.prevent="onSubmit" class="space-y-4">
      <div>
        <label class="block text-sm font-medium text-slate-700 mb-1">Email</label>
        <input
          v-model="email"
          type="email"
          autocomplete="email"
          class="w-full px-4 py-2 rounded-lg border border-slate-300 focus:ring-2 focus:ring-blue-500"
        />
        <p v-if="emailError" class="text-red-500 text-sm mt-1">{{ emailError }}</p>
      </div>
      <button
        type="submit"
        :disabled="loading"
        class="w-full bg-blue-600 text-white py-2 rounded-md hover:bg-blue-700 disabled:opacity-50"
      >
        {{ loading ? "Sending..." : "Send link" }}
      </button>
    </form>

    <p v-else class="text-sm text-green-600">
      Check your email. Click the link to sign in.
    </p>

    <p v-if="error" class="text-red-500 text-sm">{{ error }}</p>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { useMagicLink } from "../../composables/useMagicLink";

const { requestMagicLink, loading, error, success } = useMagicLink();

const email = ref("");
const emailError = ref("");

async function onSubmit() {
  emailError.value = "";
  if (!email.value.trim()) {
    emailError.value = "Email is required";
    return;
  }
  try {
    await requestMagicLink(email.value.trim());
  } catch {
    // error set by composable
  }
}
</script>

// auth-client-next/components/auth/MagicLinkForm.tsx
/**
 * components/auth/MagicLinkForm.tsx
 * Purpose: Single email field; validate with MagicLinkRequestSchema; onSubmit(data); submitted shows "Check your inbox".
 * Inputs: onSubmit(data), submitted?, error?.
 * Outputs: Renders form or success message.
 * Dependencies: auth/validation/loginSchemas, Tailwind.
 */

"use client";

import React, { useState } from "react";
import { MagicLinkRequestSchema } from "@/auth/validation/loginSchemas";
import type { MagicLinkRequest } from "@/auth/validation/loginSchemas";
import { cn } from "@/lib/utils";

interface MagicLinkFormProps {
  onSubmit: (data: MagicLinkRequest) => void;
  submitted?: boolean;
  error?: string | null;
  className?: string;
}

export function MagicLinkForm({
  onSubmit,
  submitted = false,
  error: externalError,
  className,
}: MagicLinkFormProps) {
  const [email, setEmail] = useState("");
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setFieldErrors({});
    const result = MagicLinkRequestSchema.safeParse({ email, tenantId: undefined });
    if (!result.success) {
      const errors: Record<string, string> = {};
      result.error.flatten().fieldErrors?.email?.forEach((m) => (errors.email = m));
      setFieldErrors(errors);
      return;
    }
    onSubmit(result.data);
  };

  if (submitted) {
    return (
      <div className={cn("rounded-md border border-[var(--border)] bg-muted/50 p-4 text-center", className)}>
        <p className="font-medium text-foreground">Check your inbox</p>
        <p className="mt-1 text-sm text-muted-foreground">
          We sent a magic link to <strong>{email || "your email"}</strong>. Click it to sign in.
        </p>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit} className={cn("space-y-4", className)}>
      {externalError && (
        <div
          className="rounded-md border border-destructive/50 bg-destructive/10 px-3 py-2 text-sm text-destructive"
          role="alert"
        >
          {externalError}
        </div>
      )}
      <div>
        <label htmlFor="magic-email" className="mb-1 block text-sm font-medium text-foreground">
          Email
        </label>
        <input
          id="magic-email"
          type="email"
          autoComplete="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          className={cn(
            "w-full rounded-md border border-[var(--border)] bg-background px-3 py-2 text-foreground",
            "focus:outline-none focus:ring-2 focus:ring-[var(--primary)]",
            fieldErrors.email && "border-destructive"
          )}
        />
        {fieldErrors.email && (
          <p className="mt-1 text-sm text-destructive">{fieldErrors.email}</p>
        )}
      </div>
      <button
        type="submit"
        className={cn(
          "w-full rounded-md bg-[var(--primary)] px-4 py-2 font-medium text-primary-foreground",
          "hover:opacity-90"
        )}
      >
        Send magic link
      </button>
    </form>
  );
}
