// auth-client-vue/app/components/auth/RequestAccessForm.vue
<!-- components/auth/RequestAccessForm.vue – invite_only signup. -->
<template>
  <div class="space-y-4">
    <h2 class="text-lg font-semibold">Request access</h2>
    <p class="text-sm text-slate-600">Submit your details and we’ll get back to you.</p>
    <form @submit.prevent="onSubmit" class="space-y-4">
      <div>
        <label class="block text-sm font-medium text-slate-700 mb-1">Email</label>
        <input
          v-model="email"
          type="email"
          autocomplete="email"
          class="w-full px-4 py-2 rounded-lg border border-slate-300 focus:ring-2 focus:ring-blue-500"
        />
        <p v-if="emailError" class="text-red-500 text-sm mt-1">{{ emailError }}</p>
      </div>
      <div>
        <label class="block text-sm font-medium text-slate-700 mb-1">Name (optional)</label>
        <input
          v-model="name"
          type="text"
          class="w-full px-4 py-2 rounded-lg border border-slate-300 focus:ring-2 focus:ring-blue-500"
        />
      </div>
      <div>
        <label class="block text-sm font-medium text-slate-700 mb-1">Message (optional)</label>
        <textarea
          v-model="message"
          rows="3"
          class="w-full px-4 py-2 rounded-lg border border-slate-300 focus:ring-2 focus:ring-blue-500"
        />
      </div>
      <button
        type="submit"
        :disabled="loading"
        class="w-full bg-blue-600 text-white py-2 rounded-md hover:bg-blue-700 disabled:opacity-50"
      >
        {{ loading ? "Submitting..." : "Request access" }}
      </button>
    </form>
    <p v-if="error" class="text-red-500 text-sm">{{ error }}</p>
    <p v-if="success" class="text-sm text-green-600">Request received. We’ll be in touch.</p>
    <NuxtLink to="/auth/login" class="text-sm text-blue-600 hover:underline block mt-2">Back to login</NuxtLink>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { fetchPostRequest } from "../../lib/commonApi";

const loading = ref(false);
const error = ref<string | null>(null);
const success = ref(false);
const email = ref("");
const name = ref("");
const message = ref("");
const emailError = ref("");

async function onSubmit() {
  emailError.value = "";
  error.value = null;
  if (!email.value.trim()) {
    emailError.value = "Email is required";
    return;
  }
  const re = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!re.test(email.value)) {
    emailError.value = "Enter a valid email";
    return;
  }
  loading.value = true;
  try {
    await fetchPostRequest("/api/auth/request-access", {
      body: { email: email.value.trim(), name: name.value.trim() || undefined, message: message.value.trim() || undefined },
      auth: false,
    });
    success.value = true;
  } catch (e) {
    error.value = e instanceof Error ? e.message : "Request failed";
  } finally {
    loading.value = false;
  }
}
</script>

// auth-client-next/components/auth/RequestAccessForm.tsx
/**
 * components/auth/RequestAccessForm.tsx
 * Purpose: Request access form — name?, email, company?, message?; validate with SignupRequestSchema; onSubmit(data).
 * Inputs: onSubmit(data), submitted?, error?.
 * Outputs: Renders form or "We'll be in touch" success.
 * Dependencies: auth/validation/loginSchemas, Tailwind.
 */

"use client";

import React, { useState } from "react";
import { SignupRequestSchema } from "@/auth/validation/loginSchemas";
import type { SignupRequest } from "@/auth/validation/loginSchemas";
import { cn } from "@/lib/utils";

interface RequestAccessFormProps {
  onSubmit: (data: SignupRequest) => void;
  submitted?: boolean;
  error?: string | null;
  className?: string;
}

export function RequestAccessForm({
  onSubmit,
  submitted = false,
  error: externalError,
  className,
}: RequestAccessFormProps) {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [company, setCompany] = useState("");
  const [message, setMessage] = useState("");
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setFieldErrors({});
    const result = SignupRequestSchema.safeParse({
      email,
      name: name || undefined,
      company: company || undefined,
      message: message || undefined,
      tenantId: undefined,
    });
    if (!result.success) {
      const errors: Record<string, string> = {};
      const flat = result.error.flatten().fieldErrors;
      Object.entries(flat).forEach(([k, v]) => { if (v?.[0]) errors[k] = v[0]; });
      setFieldErrors(errors);
      return;
    }
    onSubmit(result.data);
  };

  if (submitted) {
    return (
      <div className={cn("rounded-md border border-[var(--border)] bg-muted/50 p-4 text-center", className)}>
        <p className="font-medium text-foreground">We&apos;ll be in touch</p>
        <p className="mt-1 text-sm text-muted-foreground">
          Your request has been submitted. We&apos;ll contact you soon.
        </p>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit} className={cn("space-y-4", className)}>
      {externalError && (
        <div
          className="rounded-md border border-destructive/50 bg-destructive/10 px-3 py-2 text-sm text-destructive"
          role="alert"
        >
          {externalError}
        </div>
      )}
      <div>
        <label htmlFor="ra-name" className="mb-1 block text-sm font-medium text-foreground">
          Name (optional)
        </label>
        <input
          id="ra-name"
          type="text"
          autoComplete="name"
          value={name}
          onChange={(e) => setName(e.target.value)}
          className={cn(
            "w-full rounded-md border border-[var(--border)] bg-background px-3 py-2 text-foreground",
            "focus:outline-none focus:ring-2 focus:ring-[var(--primary)]"
          )}
        />
      </div>
      <div>
        <label htmlFor="ra-email" className="mb-1 block text-sm font-medium text-foreground">
          Email
        </label>
        <input
          id="ra-email"
          type="email"
          autoComplete="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          className={cn(
            "w-full rounded-md border border-[var(--border)] bg-background px-3 py-2 text-foreground",
            "focus:outline-none focus:ring-2 focus:ring-[var(--primary)]",
            fieldErrors.email && "border-destructive"
          )}
        />
        {fieldErrors.email && (
          <p className="mt-1 text-sm text-destructive">{fieldErrors.email}</p>
        )}
      </div>
      <div>
        <label htmlFor="ra-company" className="mb-1 block text-sm font-medium text-foreground">
          Company (optional)
        </label>
        <input
          id="ra-company"
          type="text"
          value={company}
          onChange={(e) => setCompany(e.target.value)}
          className={cn(
            "w-full rounded-md border border-[var(--border)] bg-background px-3 py-2 text-foreground",
            "focus:outline-none focus:ring-2 focus:ring-[var(--primary)]"
          )}
        />
      </div>
      <div>
        <label htmlFor="ra-message" className="mb-1 block text-sm font-medium text-foreground">
          Message (optional)
        </label>
        <textarea
          id="ra-message"
          rows={3}
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          className={cn(
            "w-full rounded-md border border-[var(--border)] bg-background px-3 py-2 text-foreground",
            "focus:outline-none focus:ring-2 focus:ring-[var(--primary)]"
          )}
        />
      </div>
      <button
        type="submit"
        className={cn(
          "w-full rounded-md bg-[var(--primary)] px-4 py-2 font-medium text-primary-foreground",
          "hover:opacity-90"
        )}
      >
        Request access
      </button>
    </form>
  );
}
